Try to fix requests backend import error
In some situations, this error is raised:

ImportError: cannot import name 'RequestsBackend' from partially
initialized module 'pusher.requests' (most likely due to a circular
import).

This commit fixes this error and also makes the code more organised.